### Exercícios do Cap 08 - Python Fundamentos para Análise de Dados

#### Exercício 1

In [7]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [8]:
import numpy as np

In [9]:
array1 = np.arange(0, 1000000)
lista1 = range(0, 1000000)

In [10]:
%time
array1 * 2

Wall time: 0 ns


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [11]:
%time 
lista2=list()
for num in lista1:
    num2 = num * 2
    lista2.append(num2)

Wall time: 0 ns


#### Exercício 2

In [12]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [13]:
array2 = np.arange(0, 10)

In [14]:
array2[5:8] = 0
array2

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

#### Exercício 3

In [15]:
# Crie um array de 3 dimensões e imprima a dimensão 1

In [16]:
array3 = np.array([[[[1, 2, 3], [4, 5, 6]]]])
np.shape(array3)
array3

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [17]:
array3[0]

array([[[1, 2, 3],
        [4, 5, 6]]])

#### Exercício 4

In [18]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [19]:
array4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
array4[2, :]

array([ 9, 10, 11, 12])

In [21]:
array4[0:2, 1:3]

array([[2, 3],
       [6, 7]])

#### Exercício 5

In [22]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### Exercício 6

In [24]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [25]:
cond_max = len(cond)
i = 0
while i<cond_max:
    if cond[i] == True:
        print(xarr[i])
    else:
        print(yarr[i])
    i += 1

1.1
2.2
1.3
1.4
2.5


#### Exercício 7

In [26]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [27]:
A = np.arange(0, 10)

In [28]:
np.save("testeA.npy", A)

In [29]:
B = np.load("testeA.npy")

In [30]:
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Exercícios 8

In [31]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [32]:
pd.unique(obj)

array(['c', 'a', 'd', 'b'], dtype=object)

#### Exercício 9

In [33]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [34]:
type(resp)

requests.models.Response

In [35]:
resp_df = pd.DataFrame(resp.json())
resp_df.head()

url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                   repository_url  \
0  https://api.github.com/repos/pandas-dev/pandas   
1  https://api.github.com/repos/pandas-dev/pandas   
2  https://api.github.com/repos/pandas-dev/pandas   
3  https://api.github.com/repos/pandas-dev/pandas   
4  https://api.github.com/repos/pandas-dev/pandas   

                                          labels_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                        comments_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                          events_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   

                                            html_url         id  \
0    https://github.com/pandas-dev/pandas/pull/38232  755201841   
1  https://github.com/pandas-dev/pandas/issues/38229  755073430   
2  https://github.com/pandas-dev/pandas/issues/38227  754918524   
3    https://github.com/pandas-dev/pandas/pull/38226  754909911   
4    https://github.com/pandas-dev/pandas/pull/38225  754889125   

                            node_id  number  \
0  MDExOlB1bGxSZXF1ZXN0NTMwOTU5MjIx   38232   
1          MDU6SXNzdWU3NTUwNzM0MzA=   38229   
2          MDU6SXNzdWU3NTQ5MTg1MjQ=   38227   
3  MDExOlB1bGxSZXF1ZXN0NTMwNzIyMTE5   38226   
4  MDExOlB1bGxSZXF1ZXN0NTMwNzA1NjY3   38225   

                                               title  ... milestone comments  \
0  TST: Assert msg with pytest raises in pandas/t...  ...      None        0   
1  ENH: Apply function on a column easily, mainta...  ...      None        1   
2  BUG: values are dropped when grouping on a var...  ...      None        3   
3  Rewrite dict literal for files in pandas/tests...  ...      None        1   
4   ENH: context-manager for TextFile/JSON/SASReader  ...      None        1   

             created_at            updated_at closed_at author_association  \
0  2020-12-02T11:45:09Z  2020-12-02T11:52:12Z      None        CONTRIBUTOR   
1  2020-12-02T08:51:32Z  2020-12-02T11:45:22Z      None        CONTRIBUTOR   
2  2020-12-02T04:02:55Z  2020-12-02T10:47:39Z      None               NONE   
3  2020-12-02T03:40:20Z  2020-12-02T11:00:17Z      None        CONTRIBUTOR   
4  2020-12-02T02:54:26Z  2020-12-02T07:37:27Z      None        CONTRIBUTOR   

  active_lock_reason                                       pull_request  \
0               None  {'url': 'https://api.github.com/repos/pandas-d...   
1               None                                                NaN   
2               None                                                NaN   
3               None  {'url': 'https://api.github.com/repos/pandas-d...   
4               None  {'url': 'https://api.github.com/repos/pandas-d...   

                                                body performed_via_github_app  
0  - [ ] closes #xxxx\r\n- [ ] tests added / pass...                     None  
1  I really like the pandas fluent / method chain...                     None  
2  Hello there,\r\n\r\nConsider this simple examp...   

In [36]:
resp_df2 = resp_df[['number', 'title', 'labels', 'state']]

In [37]:
resp_df2

number                                              title  \
0    38232  TST: Assert msg with pytest raises in pandas/t...   
1    38229  ENH: Apply function on a column easily, mainta...   
2    38227  BUG: values are dropped when grouping on a var...   
3    38226  Rewrite dict literal for files in pandas/tests...   
4    38225   ENH: context-manager for TextFile/JSON/SASReader   
5    38224                                   API: bool(pd.NA)   
6    38223                    TST: tighten testing assertions   
7    38222  API: make tm.assert_foo_equal kwargs keyword-o...   
8    38221  BUG: Pip 20.3 is causing Linux py38 np dev pip...   
9    38220  BUG: DataFrame.drop raising TypeError for stri...   
10   38219     Update Dockerfile to use conda-forge compilers   
11   38217  API: Groupby.idxmax drops nuisance columns, Da...   
12   38216                 Corrected the grammar in Exception   
13   38215  TST: add cases for nearest_workday and before_...   
14   38214  TST: test_is_list_like_recursion segfaults som...   
15   38213  dict rewritten as literal for files in directo...   
16   38204        Retain views with listlike indexers setitem   
17   38202      PERF: fix assert_frame_equal can be very slow   
18   38200                             TYP: @final in groupby   
19   38197          BUG: name attr in RangeIndex.intersection   
20   38195     BUG: DataFrame.idxmin/idxmax with mixed dtypes   
21   38187        BUG: groupby.rank for dt64tz, period dtypes   
22   38183           BUG: assert_frame_equal can be very slow   
23   38182  BUG/DEPR: Fix unwanted warnings from the Serie...   
24   38179  PERF: Introducing hash tables for complex64 an...   
25   38176  The error message for unsupported index on shi...   
26   38175     ENH: support nanoseconds in Period constructor   
27   38174                   REF/CLN: DataFrame.combine_first   
28   38173   BUG: array-like quantile fails on column groupby   
29   38164  REF: avoid try/except in wrapping in cython_ag...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3                                                  []  open  
4   [{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
5   [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
6   [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
7   [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
9   [{'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2...  open  
10  [{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...  open  
11  [{'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNz...  open  
12  [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
13  [{'id': 53181044, 'node_id': 'MDU6TGFiZWw1MzE4...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open  
16  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
17  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
18  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
19  [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
20  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
21  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
24  [{'id': 172091424, 'node_id': 'MDU6TGFiZWwxNzI...  open  
25  [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
26  [{'id': 60635328, 'node_id': 'MDU6TGFiZWw2MDYz...  open  
27  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open